# Generated by Django 2.2.8 on 2019-12-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0006_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='avatar2',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pole',
            name='avatar3',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
